// src/components/BottomTabBar.tsx
import React, { useState } from 'react';
import { bottomTabs } from '../data/features';

export const BottomTabBar: React.FC = () => {
  const [activeId, setActiveId] = useState(bottomTabs[0].id);

  return (
    <div className="px-6 py-2">
      <div className="flex items-center justify-around glass-card rounded-2xl py-2 px-2">
        {bottomTabs.map((tab) => {
          const isActive = activeId === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveId(tab.id)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl transition-all ${
                isActive
                  ? 'bg-blue-500 text-white shadow-md'
                  : 'text-gray-600 hover:bg-white/50'
              }`}
            >
              <span className="text-base">{tab.icon}</span>
              <span className="text-xs font-medium">{tab.label}</span>
            </button>
          );
        })}
      </div>
    </div>
  );
};

// offline-app/src/components/BottomTabBar.vue
<script setup lang="ts">
/**
 * BottomTabBar — 底部 4 个 tab(离线场景)
 *
 * tabs 由父组件传入;当前激活项走 ui store;
 * 选中后 emit('select', id),由父组件决定后续动作。
 */
import { useUiStore } from '@/stores/ui'
import type { BottomTab } from '@/data/assistantFeatures'

defineProps<{
  tabs: BottomTab[]
}>()

const emit = defineEmits<{
  select: [id: string]
}>()

const uiStore = useUiStore()

function handleClick(id: string) {
  uiStore.setActiveTab(id)
  emit('select', id)
}
</script>

<template>
  <div class="tabbar-wrap">
    <div class="tabbar glass-card">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        type="button"
        class="tab"
        :class="{ 'is-active': uiStore.activeTabId === tab.id }"
        @click="handleClick(tab.id)"
      >
        <span class="tab-icon">{{ tab.icon }}</span>
        <span class="tab-label">{{ tab.label }}</span>
      </button>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.tabbar-wrap {
  padding: 8px 24px; /* px-6 py-2 */
}

.tabbar {
  display: flex;
  align-items: center;
  justify-content: space-around;
  padding: 10px; /* 略大于 py-2,补偿行高差异 */
  border-radius: 16px; /* rounded-2xl */
  /* .glass-card 已在 template 上挂上 */
}

.tab {
  display: flex;
  align-items: center;
  gap: 6px; /* gap-1.5 */
  padding: 8px 14px; /* 略大于 py-1.5 px-3,补偿行高 */
  border: none;
  border-radius: 12px; /* rounded-xl */
  background: transparent;
  cursor: pointer;
  color: #4b5563; /* text-gray-600 */
  font: inherit;
  line-height: 1.5;
  transition: background-color 200ms, color 200ms;

  &:hover {
    background: rgba(255, 255, 255, 0.5); /* hover:bg-white/50 */
  }

  &.is-active {
    background: #3b82f6; /* bg-blue-500 */
    color: #ffffff; /* text-white */
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* shadow-md */
  }
}

.tab-icon {
  font-size: 16px; /* text-base */
  line-height: 1;
}

.tab-label {
  font-size: 12px; /* text-xs */
  font-weight: 500;
}
</style>
